config/routes.rb
Rails.application.routes.draw do
  resources :constituents
  resources :herbs

  get "dashboard/index"

  root "dashboard#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/constituency.rb
class Constituency < ApplicationRecord
    has_and_belongs_to_many :herbs
end

app/models/constituent.rb
class Constituent < ApplicationRecord
    has_and_belongs_to_many :herbs
end

app/models/herb.rb
class Herb < ApplicationRecord
    has_and_belongs_to_many :constituents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/constituents_controller.rb
class ConstituentsController < ApplicationController
  before_action :set_constituent, only: %i[ show edit update destroy ]

  # GET /constituents or /constituents.json
  def index
    @constituents = Constituent.all
  end

  # GET /constituents/1 or /constituents/1.json
  def show
  end

  # GET /constituents/new
  def new
    @constituent = Constituent.new
  end

  # GET /constituents/1/edit
  def edit
  end

  # POST /constituents or /constituents.json
  def create
    @constituent = Constituent.new(constituent_params)

    respond_to do |format|
      if @constituent.save
        format.html { redirect_to constituent_url(@constituent), notice: "Constituent was successfully created." }
        format.json { render :show, status: :created, location: @constituent }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @constituent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /constituents/1 or /constituents/1.json
  def update
    respond_to do |format|
      if @constituent.update(constituent_params)
        format.html { redirect_to constituent_url(@constituent), notice: "Constituent was successfully updated." }
        format.json { render :show, status: :ok, location: @constituent }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @constituent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /constituents/1 or /constituents/1.json
  def destroy
    @constituent.destroy

    respond_to do |format|
      format.html { redirect_to constituents_url, notice: "Constituent was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_constituent
      @constituent = Constituent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def constituent_params
      params.require(:constituent).permit(:name, :description)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    def index
    end
end

app/controllers/herbs_controller.rb
class HerbsController < ApplicationController
  before_action :set_herb, only: %i[ show edit update destroy ]

  # GET /herbs or /herbs.json
  def index
    @herbs = Herb.all
  end

  # GET /herbs/1 or /herbs/1.json
  def show
  end

  # GET /herbs/new
  def new
    @herb = Herb.new
  end

  # GET /herbs/1/edit
  def edit
  end

  # POST /herbs or /herbs.json
  def create
    @herb = Herb.new(herb_params)

    respond_to do |format|
      if @herb.save
        format.html { redirect_to herb_url(@herb), notice: "Herb was successfully created." }
        format.json { render :show, status: :created, location: @herb }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @herb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /herbs/1 or /herbs/1.json
  def update
    respond_to do |format|
      if @herb.update(herb_params)
        format.html { redirect_to herb_url(@herb), notice: "Herb was successfully updated." }
        format.json { render :show, status: :ok, location: @herb }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @herb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /herbs/1 or /herbs/1.json
  def destroy
    @herb.destroy

    respond_to do |format|
      format.html { redirect_to herbs_url, notice: "Herb was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_herb
      @herb = Herb.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def herb_params
      params.require(:herb).permit(:latin_name, :common_names, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/constituents_helper.rb
module ConstituentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/herbs_helper.rb
module HerbsHelper
end

app/views/constituents/_constituent.html.erb
<div id="<%= dom_id constituent %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= constituent.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= constituent.description %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this constituent", constituent, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this constituent', edit_constituent_path(constituent), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/constituents/_form.html.erb
<%= form_with(model: constituent, class: "contents") do |form| %>
  <% if constituent.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(constituent.errors.count, "error") %> prohibited this constituent from being saved:</h2>

      <ul>
        <% constituent.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_field :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/constituents/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing constituent</h1>

  <%= render "form", constituent: @constituent %>

  <%= link_to "Show this constituent", @constituent, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to constituents", constituents_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/constituents/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Constituents</h1>
    <%= link_to 'New constituent', new_constituent_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    <%= link_to 'Return to Dashboard', root_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="constituents" class="min-w-full">
    <%= render @constituents %>
  </div>
</div>

app/views/constituents/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New constituent</h1>

  <%= render "form", constituent: @constituent %>

  <%= link_to 'Back to constituents', constituents_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/constituents/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @constituent %>

    <%= link_to 'Edit this constituent', edit_constituent_path(@constituent), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this constituent', constituent_path(@constituent), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to constituents', constituents_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/dashboard/index.html.erb
<div class="m-1">
    <%= link_to "Go to Herbs", herbs_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
</div>
<div class="m-1">
    <%= link_to "Go to Constituents", constituents_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
</div>

app/views/herbs/_form.html.erb
<%= form_with(model: herb, class: "contents") do |form| %>
  <% if herb.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(herb.errors.count, "error") %> prohibited this herb from being saved:</h2>

      <ul>
        <% herb.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :latin_name %>
    <%= form.text_field :latin_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :common_names %>
    <%= form.text_field :common_names, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_field :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/herbs/_herb.html.erb
<div id="<%= dom_id herb %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Latin name:</strong>
    <%= herb.latin_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Common names:</strong>
    <%= herb.common_names %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= herb.description %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this herb", herb, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this herb', edit_herb_path(herb), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/herbs/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing herb</h1>

  <%= render "form", herb: @herb %>

  <%= link_to "Show this herb", @herb, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to herbs", herbs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/herbs/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Herbs</h1>
    <%= link_to 'New herb', new_herb_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    <%= link_to 'Return to Dashboard', root_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="herbs" class="min-w-full">
    <%= render @herbs %>
  </div>
</div>

app/views/herbs/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New herb</h1>

  <%= render "form", herb: @herb %>

  <%= link_to 'Back to herbs', herbs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/herbs/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @herb %>

    <%= link_to 'Edit this herb', edit_herb_path(@herb), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this herb', herb_path(@herb), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to herbs', herbs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Herbology</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>